// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_final_backend.Data;

#nullable disable

namespace proyecto_final_backend.Migrations
{
    [DbContext(typeof(proyecto_final_backendContext))]
    [Migration("20251117201414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyecto_final_backend.Models.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("caracteristicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Descripcion = "Socket LGA1700",
                            Tipo = "Compatibilidad"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Descripcion = "16GB DDR4",
                            Tipo = "Capacidad"
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Descripcion = "SSD 1TB NVMe",
                            Tipo = "Almacenamiento"
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Descripcion = "Fuente 650W",
                            Tipo = "Potencia"
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.CaracteristicaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCaracteristica")
                        .HasColumnType("int")
                        .HasColumnName("id_caracteristica");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdCaracteristica", "IdProducto")
                        .IsUnique();

                    b.ToTable("caracteristicas_productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCaracteristica = 1,
                            IdProducto = 1
                        },
                        new
                        {
                            Id = 2,
                            IdCaracteristica = 2,
                            IdProducto = 3
                        },
                        new
                        {
                            Id = 3,
                            IdCaracteristica = 3,
                            IdProducto = 4
                        },
                        new
                        {
                            Id = 4,
                            IdCaracteristica = 4,
                            IdProducto = 5
                        },
                        new
                        {
                            Id = 5,
                            IdCaracteristica = 1,
                            IdProducto = 2
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("carrito_compras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCliente = 1,
                            MontoTotal = 600.00m
                        },
                        new
                        {
                            Id = 2,
                            IdCliente = 2,
                            MontoTotal = 1500.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("correo");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "cliente@demo.com",
                            Deleted = false,
                            NombreCompleto = "Cliente Demo",
                            Telefono = "555-3000"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "juan@correo.com",
                            Deleted = false,
                            NombreCompleto = "Juan Perez",
                            Telefono = "555-4000"
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProductoPrincipal")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_principal");

                    b.Property<int>("IdProductoSecundario")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_secundario");

                    b.HasKey("Id");

                    b.HasIndex("IdProductoSecundario");

                    b.HasIndex("IdProductoPrincipal", "IdProductoSecundario")
                        .IsUnique();

                    b.ToTable("componentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdProductoPrincipal = 1,
                            IdProductoSecundario = 2
                        },
                        new
                        {
                            Id = 2,
                            IdProductoPrincipal = 1,
                            IdProductoSecundario = 3
                        },
                        new
                        {
                            Id = 3,
                            IdProductoPrincipal = 2,
                            IdProductoSecundario = 3
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteGarantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdGarantia")
                        .HasColumnType("int")
                        .HasColumnName("id_garantia");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("IdGarantia");

                    b.HasIndex("IdProducto", "IdGarantia")
                        .IsUnique();

                    b.ToTable("componentes_garantias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = (byte)1,
                            IdGarantia = 1,
                            IdProducto = 4
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = (byte)1,
                            IdGarantia = 2,
                            IdProducto = 1
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdOrdenEnsamble")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_ensamble");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdenEnsamble");

                    b.HasIndex("IdProducto", "IdOrdenEnsamble")
                        .IsUnique();

                    b.ToTable("componentes_ordenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = (byte)1,
                            IdOrdenEnsamble = 1,
                            IdProducto = 1,
                            Precio = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = (byte)1,
                            IdOrdenEnsamble = 2,
                            IdProducto = 3,
                            Precio = 600.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteReparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdReparacion");

                    b.HasIndex("IdProducto", "IdReparacion")
                        .IsUnique();

                    b.ToTable("componentes_reparaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = (byte)1,
                            IdProducto = 5,
                            IdReparacion = 1,
                            Precio = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = (byte)1,
                            IdProducto = 1,
                            IdReparacion = 2,
                            Precio = 700.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor")
                        .IsUnique();

                    b.ToTable("compras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Fecha = new DateOnly(2025, 1, 5),
                            IdProveedor = 1,
                            MontoTotal = 14000.00m
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Fecha = new DateOnly(2025, 2, 5),
                            IdProveedor = 2,
                            MontoTotal = 8500.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdCompra")
                        .IsUnique();

                    b.HasIndex("IdProducto")
                        .IsUnique();

                    b.ToTable("detalles_compras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = (byte)10,
                            Deleted = false,
                            IdCompra = 1,
                            IdProducto = 1,
                            Precio = 1400.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = (byte)10,
                            Deleted = false,
                            IdCompra = 2,
                            IdProducto = 4,
                            Precio = 850.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto")
                        .IsUnique();

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("detalles_ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = (byte)1,
                            Deleted = false,
                            IdProducto = 2,
                            IdVenta = 1,
                            Precio = 2200.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = (byte)1,
                            Deleted = false,
                            IdProducto = 1,
                            IdVenta = 2,
                            Precio = 1500.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioDevolucion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_devolucion");

                    b.HasKey("Id");

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("devoluciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            IdVenta = 1,
                            PrecioDevolucion = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            IdVenta = 2,
                            PrecioDevolucion = 1500.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DevolucionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDevolucion")
                        .HasColumnType("int")
                        .HasColumnName("id_devolucion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("IdDevolucion");

                    b.HasIndex("IdProducto", "IdDevolucion")
                        .IsUnique();

                    b.ToTable("devoluciones_productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdDevolucion = 1,
                            IdProducto = 5
                        },
                        new
                        {
                            Id = 2,
                            IdDevolucion = 2,
                            IdProducto = 1
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Garantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("garantias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Estado = (byte)1,
                            Fecha = new DateOnly(2025, 1, 15),
                            IdUsuario = 1,
                            IdVenta = 1
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Estado = (byte)1,
                            Fecha = new DateOnly(2025, 2, 15),
                            IdUsuario = 2,
                            IdVenta = 2
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.OrdenEnsamble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioEnsamble")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_ensamble");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("ordenes_ensambles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Estado = (byte)1,
                            IdUsuario = 1,
                            IdVenta = 1,
                            PrecioEnsamble = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Estado = (byte)1,
                            IdUsuario = 2,
                            IdVenta = 2,
                            PrecioEnsamble = 200.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Nuevo")
                        .HasColumnType("bit")
                        .HasColumnName("nuevo");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<byte>("Stock")
                        .HasColumnType("tinyint")
                        .HasColumnName("stock");

                    b.Property<byte>("StockMinimo")
                        .HasColumnType("tinyint")
                        .HasColumnName("stock_minimo");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PROD-001",
                            Deleted = false,
                            Imagen = "mb-a1.png",
                            Nombre = "Tarjeta Madre A1",
                            Nuevo = true,
                            Precio = 1500.00m,
                            Stock = (byte)50,
                            StockMinimo = (byte)10,
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PROD-002",
                            Deleted = false,
                            Imagen = "cpu-x.png",
                            Nombre = "Procesador X",
                            Nuevo = true,
                            Precio = 2200.00m,
                            Stock = (byte)35,
                            StockMinimo = (byte)8,
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PROD-003",
                            Deleted = false,
                            Imagen = "ram-16gb.png",
                            Nombre = "Memoria 16GB",
                            Nuevo = true,
                            Precio = 600.00m,
                            Stock = (byte)80,
                            StockMinimo = (byte)20,
                            Tipo = (byte)2
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "PROD-004",
                            Deleted = false,
                            Imagen = "ssd-1tb.png",
                            Nombre = "SSD 1TB",
                            Nuevo = true,
                            Precio = 900.00m,
                            Stock = (byte)60,
                            StockMinimo = (byte)15,
                            Tipo = (byte)2
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PROD-005",
                            Deleted = false,
                            Imagen = "psu-650w.png",
                            Nombre = "Fuente 650W",
                            Nuevo = false,
                            Precio = 500.00m,
                            Stock = (byte)40,
                            StockMinimo = (byte)10,
                            Tipo = (byte)3
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ProductoCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdCarrito")
                        .HasColumnType("int")
                        .HasColumnName("id_carrito");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdProducto", "IdCarrito")
                        .IsUnique();

                    b.ToTable("productos_carrito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = (byte)1,
                            Deleted = false,
                            IdCarrito = 1,
                            IdProducto = 3,
                            Precio = 600.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = (byte)1,
                            Deleted = false,
                            IdCarrito = 2,
                            IdProducto = 1,
                            Precio = 1500.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("correo");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre_contacto");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "contacto@techparts.com",
                            Deleted = false,
                            Nombre = "Tech Parts",
                            NombreContacto = "Ana Lopez",
                            Telefono = "555-1000"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "ventas@compudistrib.com",
                            Deleted = false,
                            Nombre = "CompuDistrib",
                            NombreContacto = "Luis Garcia",
                            Telefono = "555-2000"
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVenta");

                    b.ToTable("reparaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            IdUsuario = 1,
                            IdVenta = 1,
                            Precio = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            IdUsuario = 2,
                            IdVenta = 2,
                            Precio = 700.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Descripcion = "Acceso total al sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Descripcion = "Gestión de ventas",
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("nombre_usuario");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario");

                    b.HasKey("Id");

                    b.HasIndex("IdRol")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "admin123",
                            Deleted = false,
                            IdRol = 1,
                            NombreCompleto = "Usuario Administrador",
                            NombreUsuario = "admin",
                            Salario = 0m
                        },
                        new
                        {
                            Id = 2,
                            Contrasena = "vendedor123",
                            Deleted = false,
                            IdRol = 2,
                            NombreCompleto = "Usuario Vendedor",
                            NombreUsuario = "vendedor",
                            Salario = 0m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Fecha = new DateOnly(2025, 1, 1),
                            IdCliente = 1,
                            IdUsuario = 1,
                            MontoTotal = 2200.00m
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Fecha = new DateOnly(2025, 2, 1),
                            IdCliente = 2,
                            IdUsuario = 2,
                            MontoTotal = 1500.00m
                        });
                });

            modelBuilder.Entity("proyecto_final_backend.Models.CaracteristicaProducto", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Caracteristica", "Caracteristica")
                        .WithMany("CaracteristicasProducto")
                        .HasForeignKey("IdCaracteristica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("CaracteristicasProducto")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Carrito", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Cliente", "Cliente")
                        .WithOne("Carrito")
                        .HasForeignKey("proyecto_final_backend.Models.Carrito", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Componente", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Producto", "ProductoPrincipal")
                        .WithMany("ComponentesPrincipales")
                        .HasForeignKey("IdProductoPrincipal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "ProductoSecundario")
                        .WithMany("ComponentesSecundarios")
                        .HasForeignKey("IdProductoSecundario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoPrincipal");

                    b.Navigation("ProductoSecundario");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteGarantia", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Garantia", "Garantia")
                        .WithMany("Componentes")
                        .HasForeignKey("IdGarantia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ComponentesGarantias")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garantia");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteOrden", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.OrdenEnsamble", "OrdenEnsamble")
                        .WithMany("Componentes")
                        .HasForeignKey("IdOrdenEnsamble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ComponentesOrdenes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenEnsamble");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteReparacion", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ComponentesReparaciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Reparacion", "Reparacion")
                        .WithMany("Componentes")
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Compra", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleCompra", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleVenta", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Devolucion", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Devoluciones")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DevolucionProducto", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Devolucion", "Devolucion")
                        .WithMany("DevolucionesProducto")
                        .HasForeignKey("IdDevolucion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("DevolucionesProducto")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devolucion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Garantia", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("Garantias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Garantias")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.OrdenEnsamble", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("OrdenesEnsamble")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithOne("OrdenEnsamble")
                        .HasForeignKey("proyecto_final_backend.Models.OrdenEnsamble", "IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ProductoCarrito", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Carrito", "Carrito")
                        .WithMany("ProductosCarrito")
                        .HasForeignKey("IdCarrito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ProductosCarrito")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Reparacion", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Usuario", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Venta", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Caracteristica", b =>
                {
                    b.Navigation("CaracteristicasProducto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Carrito", b =>
                {
                    b.Navigation("ProductosCarrito");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Cliente", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Devolucion", b =>
                {
                    b.Navigation("DevolucionesProducto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Garantia", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.OrdenEnsamble", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Producto", b =>
                {
                    b.Navigation("CaracteristicasProducto");

                    b.Navigation("ComponentesGarantias");

                    b.Navigation("ComponentesOrdenes");

                    b.Navigation("ComponentesPrincipales");

                    b.Navigation("ComponentesReparaciones");

                    b.Navigation("ComponentesSecundarios");

                    b.Navigation("DetallesCompra");

                    b.Navigation("DetallesVenta");

                    b.Navigation("DevolucionesProducto");

                    b.Navigation("ProductosCarrito");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Reparacion", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Usuario", b =>
                {
                    b.Navigation("Garantias");

                    b.Navigation("OrdenesEnsamble");

                    b.Navigation("Reparaciones");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Devoluciones");

                    b.Navigation("Garantias");

                    b.Navigation("OrdenEnsamble");

                    b.Navigation("Reparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
