// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_final_backend.Data;

#nullable disable

namespace proyecto_final_backend.Migrations
{
    [DbContext(typeof(proyecto_final_backendContext))]
    [Migration("20251102175024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyecto_final_backend.Models.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .IsUnique();

                    b.ToTable("caracteristicas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.CaracteristicaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCaracteristica")
                        .HasColumnType("int")
                        .HasColumnName("id_caracteristica");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdCaracteristica", "IdProducto")
                        .IsUnique();

                    b.ToTable("caracteristicas_productos");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("carrito_compras");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("correo");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProductoPrincipal")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_principal");

                    b.Property<int>("IdProductoSecundario")
                        .HasColumnType("int")
                        .HasColumnName("id_producto_secundario");

                    b.HasKey("Id");

                    b.HasIndex("IdProductoSecundario");

                    b.HasIndex("IdProductoPrincipal", "IdProductoSecundario")
                        .IsUnique();

                    b.ToTable("componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteGarantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdGarantia")
                        .HasColumnType("int")
                        .HasColumnName("id_garantia");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("IdGarantia");

                    b.HasIndex("IdProducto", "IdGarantia")
                        .IsUnique();

                    b.ToTable("componentes_garantias");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdOrdenEnsamble")
                        .HasColumnType("int")
                        .HasColumnName("id_orden_ensamble");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdenEnsamble");

                    b.HasIndex("IdProducto", "IdOrdenEnsamble")
                        .IsUnique();

                    b.ToTable("componentes_ordenes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteReparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdReparacion")
                        .HasColumnType("int")
                        .HasColumnName("id_reparacion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdReparacion");

                    b.HasIndex("IdProducto", "IdReparacion")
                        .IsUnique();

                    b.ToTable("componentes_reparaciones");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor")
                        .IsUnique();

                    b.ToTable("compras");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdCompra")
                        .IsUnique();

                    b.HasIndex("IdProducto")
                        .IsUnique();

                    b.ToTable("detalles_compras");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto")
                        .IsUnique();

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("detalles_ventas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioDevolucion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_devolucion");

                    b.HasKey("Id");

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("devoluciones");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DevolucionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDevolucion")
                        .HasColumnType("int")
                        .HasColumnName("id_devolucion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("Id");

                    b.HasIndex("IdDevolucion");

                    b.HasIndex("IdProducto", "IdDevolucion")
                        .IsUnique();

                    b.ToTable("devolucion_producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Garantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("garantias");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.OrdenEnsamble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint")
                        .HasColumnName("estado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioEnsamble")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_ensamble");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("ordenes_ensambles");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Nuevo")
                        .HasColumnType("bit")
                        .HasColumnName("nuevo");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<byte>("Stock")
                        .HasColumnType("tinyint")
                        .HasColumnName("stock");

                    b.Property<byte>("StockMinimo")
                        .HasColumnType("tinyint")
                        .HasColumnName("stock_minimo");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("productos");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ProductoCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Cantidad")
                        .HasColumnType("tinyint")
                        .HasColumnName("cantidad");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdCarrito")
                        .HasColumnType("int")
                        .HasColumnName("id_carrito");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdProducto", "IdCarrito")
                        .IsUnique();

                    b.ToTable("productos_carrito");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("correo");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre_contacto");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVenta");

                    b.ToTable("reparaciones");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("nombre_usuario");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salario");

                    b.HasKey("Id");

                    b.HasIndex("IdRol")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("ventas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.CaracteristicaProducto", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Caracteristica", "Caracteristica")
                        .WithMany("CaracteristicasProducto")
                        .HasForeignKey("IdCaracteristica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("CaracteristicasProducto")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Carrito", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Cliente", "Cliente")
                        .WithOne("Carrito")
                        .HasForeignKey("proyecto_final_backend.Models.Carrito", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Componente", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Producto", "ProductoPrincipal")
                        .WithMany("ComponentesPrincipales")
                        .HasForeignKey("IdProductoPrincipal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "ProductoSecundario")
                        .WithMany("ComponentesSecundarios")
                        .HasForeignKey("IdProductoSecundario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoPrincipal");

                    b.Navigation("ProductoSecundario");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteGarantia", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Garantia", "Garantia")
                        .WithMany("Componentes")
                        .HasForeignKey("IdGarantia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ComponentesGarantias")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garantia");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteOrden", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.OrdenEnsamble", "OrdenEnsamble")
                        .WithMany("Componentes")
                        .HasForeignKey("IdOrdenEnsamble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ComponentesOrdenes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenEnsamble");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ComponenteReparacion", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ComponentesReparaciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Reparacion", "Reparacion")
                        .WithMany("Componentes")
                        .HasForeignKey("IdReparacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Compra", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleCompra", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DetalleVenta", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Devolucion", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Devoluciones")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.DevolucionProducto", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Devolucion", "Devolucion")
                        .WithMany("DevolucionesProducto")
                        .HasForeignKey("IdDevolucion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("DevolucionesProducto")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devolucion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Garantia", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("Garantias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Garantias")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.OrdenEnsamble", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("OrdenesEnsamble")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithOne("OrdenEnsamble")
                        .HasForeignKey("proyecto_final_backend.Models.OrdenEnsamble", "IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.ProductoCarrito", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Carrito", "Carrito")
                        .WithMany("ProductosCarrito")
                        .HasForeignKey("IdCarrito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Producto", "Producto")
                        .WithMany("ProductosCarrito")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Reparacion", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Venta", "Venta")
                        .WithMany("Reparaciones")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Usuario", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Venta", b =>
                {
                    b.HasOne("proyecto_final_backend.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("proyecto_final_backend.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Caracteristica", b =>
                {
                    b.Navigation("CaracteristicasProducto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Carrito", b =>
                {
                    b.Navigation("ProductosCarrito");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Cliente", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Devolucion", b =>
                {
                    b.Navigation("DevolucionesProducto");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Garantia", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.OrdenEnsamble", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Producto", b =>
                {
                    b.Navigation("CaracteristicasProducto");

                    b.Navigation("ComponentesGarantias");

                    b.Navigation("ComponentesOrdenes");

                    b.Navigation("ComponentesPrincipales");

                    b.Navigation("ComponentesReparaciones");

                    b.Navigation("ComponentesSecundarios");

                    b.Navigation("DetallesCompra");

                    b.Navigation("DetallesVenta");

                    b.Navigation("DevolucionesProducto");

                    b.Navigation("ProductosCarrito");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Reparacion", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Usuario", b =>
                {
                    b.Navigation("Garantias");

                    b.Navigation("OrdenesEnsamble");

                    b.Navigation("Reparaciones");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("proyecto_final_backend.Models.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Devoluciones");

                    b.Navigation("Garantias");

                    b.Navigation("OrdenEnsamble");

                    b.Navigation("Reparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
